sudo: required

before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq liblapack-dev libopenblas-dev libatlas-dev 

language: python
python:
  - "2.7_with_system_site_packages"
# command to install dependencies
install:
  - "pip install -r pip_req.txt"
# command to run tests
script: nosetests --all-modules