# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PVE_control.ui'
#
# Created: Wed Apr 13 05:20:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(449, 331)
        self.gridLayout_5 = QtGui.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_P = QtGui.QLabel(Form)
        self.label_P.setObjectName("label_P")
        self.gridLayout.addWidget(self.label_P, 0, 0, 1, 1)
        self.doubleSpinBox_P = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_P.setMinimum(1.0)
        self.doubleSpinBox_P.setMaximum(4.0)
        self.doubleSpinBox_P.setSingleStep(0.01)
        self.doubleSpinBox_P.setProperty("value", 3.0)
        self.doubleSpinBox_P.setObjectName("doubleSpinBox_P")
        self.gridLayout.addWidget(self.doubleSpinBox_P, 1, 0, 1, 1)
        self.radioButton_P = QtGui.QRadioButton(Form)
        self.radioButton_P.setText("")
        self.radioButton_P.setObjectName("radioButton_P")
        self.gridLayout.addWidget(self.radioButton_P, 3, 0, 1, 1)
        self.verticalSlider_P = QtGui.QSlider(Form)
        self.verticalSlider_P.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_P.setObjectName("verticalSlider_P")
        self.gridLayout.addWidget(self.verticalSlider_P, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_v = QtGui.QLabel(Form)
        self.label_v.setObjectName("label_v")
        self.gridLayout_2.addWidget(self.label_v, 0, 0, 1, 1)
        self.doubleSpinBox_v = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_v.setMinimum(1.0)
        self.doubleSpinBox_v.setMaximum(4.0)
        self.doubleSpinBox_v.setSingleStep(0.01)
        self.doubleSpinBox_v.setProperty("value", 3.0)
        self.doubleSpinBox_v.setObjectName("doubleSpinBox_v")
        self.gridLayout_2.addWidget(self.doubleSpinBox_v, 1, 0, 1, 1)
        self.verticalSlider_v = QtGui.QSlider(Form)
        self.verticalSlider_v.setMaximum(99)
        self.verticalSlider_v.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_v.setObjectName("verticalSlider_v")
        self.gridLayout_2.addWidget(self.verticalSlider_v, 2, 0, 1, 1)
        self.radioButton_v = QtGui.QRadioButton(Form)
        self.radioButton_v.setText("")
        self.radioButton_v.setObjectName("radioButton_v")
        self.gridLayout_2.addWidget(self.radioButton_v, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_E = QtGui.QLabel(Form)
        self.label_E.setObjectName("label_E")
        self.gridLayout_3.addWidget(self.label_E, 0, 0, 1, 1)
        self.doubleSpinBox_E = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_E.setMinimum(20.0)
        self.doubleSpinBox_E.setMaximum(400.0)
        self.doubleSpinBox_E.setSingleStep(2.0)
        self.doubleSpinBox_E.setProperty("value", 220.0)
        self.doubleSpinBox_E.setObjectName("doubleSpinBox_E")
        self.gridLayout_3.addWidget(self.doubleSpinBox_E, 1, 0, 1, 1)
        self.verticalSlider_E = QtGui.QSlider(Form)
        self.verticalSlider_E.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_E.setObjectName("verticalSlider_E")
        self.gridLayout_3.addWidget(self.verticalSlider_E, 2, 0, 1, 1)
        self.radioButton_E = QtGui.QRadioButton(Form)
        self.radioButton_E.setText("")
        self.radioButton_E.setObjectName("radioButton_E")
        self.gridLayout_3.addWidget(self.radioButton_E, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_S = QtGui.QLabel(Form)
        self.label_S.setObjectName("label_S")
        self.gridLayout_4.addWidget(self.label_S, 0, 0, 1, 1)
        self.doubleSpinBox_S = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_S.setMaximum(69.16)
        self.doubleSpinBox_S.setSingleStep(0.01)
        self.doubleSpinBox_S.setObjectName("doubleSpinBox_S")
        self.gridLayout_4.addWidget(self.doubleSpinBox_S, 1, 0, 1, 1)
        self.verticalSlider_S = QtGui.QSlider(Form)
        self.verticalSlider_S.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_S.setObjectName("verticalSlider_S")
        self.gridLayout_4.addWidget(self.verticalSlider_S, 2, 0, 1, 1)
        self.radioButton_S = QtGui.QRadioButton(Form)
        self.radioButton_S.setText("")
        self.radioButton_S.setChecked(True)
        self.radioButton_S.setObjectName("radioButton_S")
        self.gridLayout_4.addWidget(self.radioButton_S, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 3, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.EOSgroupBox = QtGui.QGroupBox(Form)
        self.EOSgroupBox.setMaximumSize(QtCore.QSize(80, 500))
        self.EOSgroupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.EOSgroupBox.setObjectName("EOSgroupBox")
        self.Ideal_button = QtGui.QRadioButton(self.EOSgroupBox)
        self.Ideal_button.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.Ideal_button.setChecked(True)
        self.Ideal_button.setObjectName("Ideal_button")
        self.Shaw_button = QtGui.QRadioButton(self.EOSgroupBox)
        self.Shaw_button.setGeometry(QtCore.QRect(0, 40, 107, 20))
        self.Shaw_button.setObjectName("Shaw_button")
        self.gridLayout_6.addWidget(self.EOSgroupBox, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_P.setToolTip(QtGui.QApplication.translate("Form", "Pressure / 10^10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_P.setText(QtGui.QApplication.translate("Form", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_P.setToolTip(QtGui.QApplication.translate("Form", "Make P constant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_v.setToolTip(QtGui.QApplication.translate("Form", "Volume / 10^-6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_v.setText(QtGui.QApplication.translate("Form", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_v.setToolTip(QtGui.QApplication.translate("Form", "Make V constant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_E.setToolTip(QtGui.QApplication.translate("Form", "Energy / 10^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_E.setText(QtGui.QApplication.translate("Form", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_E.setToolTip(QtGui.QApplication.translate("Form", "Make E constant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_S.setToolTip(QtGui.QApplication.translate("Form", "Entropy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_S.setText(QtGui.QApplication.translate("Form", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_S.setToolTip(QtGui.QApplication.translate("Form", "Make S constant", None, QtGui.QApplication.UnicodeUTF8))
        self.EOSgroupBox.setTitle(QtGui.QApplication.translate("Form", "EOS", None, QtGui.QApplication.UnicodeUTF8))
        self.Ideal_button.setText(QtGui.QApplication.translate("Form", "Ideal", None, QtGui.QApplication.UnicodeUTF8))
        self.Shaw_button.setText(QtGui.QApplication.translate("Form", "Shaw", None, QtGui.QApplication.UnicodeUTF8))

